### PR TITLE
Modernize standards and remove redundant deps

### PR DESCRIPTION
**Pull request by mihaeu**
Hey there,

thanks for this project! 

I was unable to use it for a project of mine because of the required math extension (which is actually not required by the code).

This PR:

 - adds whitelists for phpunit coverage
 - fixes composer dependencies with proper version constraints and separation of dev- prod-reqs
 - adds composer.lock file (recommended by the Composer project to avoid surprises in production)

Is this fine with you?

### CODE REVIEW

**Comment by mihaeu** [comment]
The CLAassistant doesn't seem to realize that I signed the CLA. Am I missing something?

**Comment by mihaeu** [comment]
Is anyone processing active PRs for this repo?

**Comment by baev** [comment]
@mihaeu sorry for the delay

> The CLAassistant doesn't seem to realize that I signed the CLA. Am I missing something?

Seems like the email you are using to commit is not specified in Github settings.

**Comment by mihaeu** [comment]
Thanks @baev 

> Seems like the email you are using to commit is not specified in Github settings.

I missed the part where it said exactly what the problem is :) I added the email address and not when I click on the CLA it tells me that it's already signed, but the build state is unchanged. Can you manually trigger a re-check?

**Comment by mihaeu** [comment]
> all good now +1 (you missed part where you can trigger recheck by clicking the link smile )

Friday, 4pm :) thanks for your patience ;)

**Comment by baev** [comment]
https://github.com/allure-framework/allure-php-commons/releases/tag/1.1.5

**Pull request merged**
